### ISSUE TITLE
2019-08-23-action4: add use absolute URIs to BPs (Benjamin Young)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#100]
add use absolute URIs to BPs (Benjamin Young) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-08-23-json-ld#action4))

Cc: @BigBlueHat

**Comment by BigBlueHat** [comment]
I'm going to close this one in favor of the issue on the Best Practices repo (linked above).
