### ISSUE TITLE
2019-08-23-action1: alert security as to the questionnaire responses (#89) and intend to keep going (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#102]
alert security as to the questionnaire responses (#89) and intend to keep going (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-08-23-json-ld#action1))

Cc: @azaroth42

**Comment by azaroth42** [comment]
Done.
