### ISSUE TITLE
Final fate of the json-ld short names?

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#103]
This issue came up in https://github.com/w3c/pub-manifest/issues/29 with regard to referencing our spec. What do we plan for our final spec? Will it use the json-ld short name, ie, "hiding" the previous versions, or would we want a completely new "branch" and stick to json-ld11? It is important to make clear to other specs that want to refer to json-ld...

**Comment by akuckartz** [comment]
As a user I expect "json-ld" to point to the most current spec.

**Comment by iherman** [comment]
> We registered short-names with "json-ld11" ("json-ld11", "json-ld11-api", "json-ld11-framing"). We also reference the previous spec, so "json-ld" should continue to point to the 1.0 spec.

This is the situation today indeed. However, there may be some flexibility that we can discuss with the Webmaster (maybe in Fukuoka?). (See, e.g., https://www.w3.org/2005/05/tr-versions.html#shortnames.)

I propose we try to establish a scheme that we could live with, and then see what can be implemented.

**Comment by iherman** [comment]
A possibility may be:

/TR/json-ld -> points to the latest _published_ recommendation   
/TR/json-ld10 -> points to the highest level of 1.0  
/TR/json-ld11 -> points to the highest level of 1.1  

etc.

**Comment by iherman** [comment]
@gkellogg frankly, I don't know exactly. I am happy to discuss this with the Webmaster, as soon as we agree what we want...

**Comment by azaroth42** [comment]
:+1: to json-ld10 / json-ld11 / (etc) and json-ld as a pointer to the most recent.

**Comment by iherman** [comment]
Ok. I will contact our wise people in the W3C team to see what is possible for later.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-08-30-json-ld#section5-1).

- `ACTION:  contact w3 team to determine possibility of json-ld shortname pointing to latest version (Ivan Herman)`
<details><summary><i class="differentiate">View the transcript</i></summary>
Final short names<br/>
Rob Sanderson: See WG issue #103<br/>
Rob Sanderson: Ivan raised this issue. What should ‘jdonld’ point to in the future?<br/>
… 1.0 as it currently does, or the most recent version of the spec?<br/>
… There has been some discussion on the list.<br/>
… The suggestion is that ‘jsonld’ always points to the most recent,<br/>
… and ‘jsonld10’ and ‘jsonld11’ point to respective versions.<br/>
Ivan Herman: I have to check with the webmasters what exactly the rules are.<br/>
… If the WG is fine with this solution, I can start the discussion with them.<br/>
… Some people like pointin to the very last working draft,<br/>
… I’m not sure that’s a good idea, but we can discuss this later.<br/>
Gregg Kellogg: my concern is that this will change what ‘jsonld’ points to…<br/>
Ivan Herman: we need not solve this before CR<br/>
Rob Sanderson: are there other specifications who reference JSON-LD 1.0 via jsonld?<br/>
… this could lead to strange things for readers,<br/>
… especially if those spec say something like “JSON-LD does not support this”,<br/>
… while in fact JSON-LD 1.1 does.<br/>
Pierre-Antoine Champin: Just wanted to point out that JSON-LD pointing to something else is a matter of perspective. Currently it does point to the latest version<br/>
… I would argue it doesn’t change what we point to. Rob’s arguemtn about other specs is a good point.<br/>
Ivan Herman: to the best of my knowledge, no W3C spec referencing JSON-LD extend it in a way that azaroth suggests<br/>
… Groups out there may have done something nasty in that line,<br/>
… but well, they shouldn’t have been nasty.<br/>
Gregg Kellogg: if a spec has particular version dependency, they should point to a precise version<br/>
Benjamin Young: Activity Streams has its own media-type, because JSON-LD didn’t support lists of lists.<br/>
… What would be the impact on testing for other specs?<br/>
Rob Sanderson: +1 to dlongley<br/>
Ivan Herman: +1<br/>
Gregg Kellogg: +1<br/>
Benjamin Young: for the curious: <a href="https://www.specref.org/?q=json-ld">https://www.specref.org/?q=json-ld</a><br/>
Dave Longley: I think that the benefit of having the latest version come up for ‘jsonld’ outweights the potential costs.<br/>
Action #1: contact w3 team to determine possibility of json-ld shortname pointing to latest version (Ivan Herman)<br/>
Gregg Kellogg: what does this mean for us? Sounds like “nothing” in the short term,<br/>
… except changing our references from ‘jsonld’ to ‘jsonld10’.<br/>
Ivan Herman: correct<br/>
</details>

**Comment by iherman** [comment]
(Got the answer from the Webmaster)

First of all, there is already a general setup to use common short names for versioned documents: see https://github.com/w3c/tr-pages/wiki/Latest-versions-proposal-for-leveled-specifications. Looking at that page, here is what we already have:

- https://www.w3.org/TR/json-ld/ -> http://www.w3.org/TR/2014/REC-json-ld-20140116/
- https://www.w3.org/TR/json-ld1/ -> http://www.w3.org/TR/2014/REC-json-ld-20140116/
- https://www.w3.org/TR/json-ld/upcoming/ -> https://www.w3.org/TR/2019/WD-json-ld11-20190805/
- https://www.w3.org/TR/json-ld/latest/ -> http://www.w3.org/TR/2014/REC-json-ld-20140116/

As a WG we can decide whether https://www.w3.org/TR/json-ld/ should point to: 

- https://www.w3.org/TR/json-ld/upcoming/ meaning it always points at the latest CR, PR, or Rec draft (this is a bit the HTML5 model of 'living standard'); or
- https://www.w3.org/TR/json-ld/latest/ meaning it points at our latest recommendation

We can add this to our CR request. My feeling is that our preference would to to the latter, which means that once the REC is published, that one will appear as the top level.

**Comment by azaroth42** [comment]
:+1: to latest, rather than upcoming
