### ISSUE TITLE
2019-08-30-action3: email Coralie regarding announcement at TPAC (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#104]
email Coralie regarding announcement at TPAC (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-08-30-json-ld#action3))

Cc: @azaroth42

**Comment by azaroth42** [comment]
Done and published in members summary :)
