### ISSUE TITLE
2019-09-06-action2: add software version DOAP property to report template (Gregg Kellogg)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#109]
add software version DOAP property to report template (Gregg Kellogg) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-09-06-json-ld#action2))

Cc: @gkellogg

**Comment by gkellogg** [comment]
Fixed in https://github.com/w3c/json-ld-api/pull/147.
