### ISSUE TITLE
2019-09-06-action4: add session idea for [https://www.w3.org/wiki/TPAC/2019/SessionIdeas](https://www.w3.org/wiki/TPAC/2019/SessionIdeas) (Gregg Kellogg)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#110]
add session idea for [https://www.w3.org/wiki/TPAC/2019/SessionIdeas](https://www.w3.org/wiki/TPAC/2019/SessionIdeas) (Gregg Kellogg) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-09-06-json-ld#action4))

Cc: @gkellogg

**Comment by gkellogg** [comment]
Done https://www.w3.org/wiki/TPAC/2019/SessionIdeas#JSON-LD_1.1_Update.
