### ISSUE TITLE
2019-09-19-action1: write a couple paragraphs + example(s) for explaining expanded form and its use (Gregg Kellogg)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#111]
write a couple paragraphs + example(s) for explaining expanded form and its use (Gregg Kellogg) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-09-19-json-ld#action1))

Cc: @gkellogg

**Comment by gkellogg** [comment]
Seems like this was done some time ago.
