### ISSUE TITLE
2019-09-20-action1: determine if `@prefix: false` will prevent the term from being used in expanding IRIs, and file an issue if it does (Gregg Kellogg)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#112]
determine if `@prefix: false` will prevent the term from being used in expanding IRIs, and file an issue if it does (Gregg Kellogg) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-09-20-json-ld#action1))

Cc: @gkellogg

**Comment by gkellogg** [comment]
Tests already exist for this, @pchampin adding a couple of more.
