### ISSUE TITLE
2019-09-20-action2: send email to schema.org CG when final WD pre CR is available for review (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#113]
send email to schema.org CG when final WD pre CR is available for review (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-09-20-json-ld#action2))

Cc: @azaroth42

**Comment by azaroth42** [comment]
Done per #114
