### ISSUE TITLE
2019-09-20-action3: send email to schema earlier (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#114]
send email to schema earlier (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-09-20-json-ld#action3))

Cc: @azaroth42

**Comment by akuckartz** [comment]
The "see details" link is broken.

**Comment by iherman** [comment]
Fixed

**Comment by azaroth42** [comment]
Completed: https://lists.w3.org/Archives/Public/public-schemaorg/2019Sep/0006.html
