### ISSUE TITLE
2019-10-04-action3: create issue on values of language maps not including `@direction` (Gregg Kellogg)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#117]
create issue on values of language maps not including `@direction` (Gregg Kellogg) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-10-04-json-ld#action3))

Cc: @gkellogg

**Comment by gkellogg** [comment]
Created https://github.com/w3c/json-ld-syntax/issues/280.
