### ISSUE TITLE
2019-10-18-action2: find CG issues and reference in CR request wiki page (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#120]
find CG issues and reference in CR request wiki page (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-10-18-json-ld#action2))

Cc: @azaroth42

**Comment by azaroth42** [comment]
Done here too: https://github.com/w3c/json-ld-wg/wiki/%5BJSON-LD-WG%5D-CR-transition-for-json-ld11,-json-ld11-api,-and-json-ld11-framing
