### ISSUE TITLE
2019-10-26-action4: comment in issue inviting DID WG to JSON-LD WG regular call next week to discuss (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#122]
comment in issue inviting DID WG to JSON-LD WG regular call next week to discuss (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-10-26-json-ld#action4))

Cc: @azaroth42

**Comment by azaroth42** [comment]
https://github.com/w3c/did-spec/issues/1#issuecomment-546503290
