### ISSUE TITLE
2019-11-01-action1: contact IETF about the multiple pluses in the JSON-LD registration (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#126]
contact IETF about the multiple pluses in the JSON-LD registration (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-11-01-json-ld#action1))

Cc: @azaroth42

**Comment by azaroth42** [comment]
Done.
