### ISSUE TITLE
2019-11-15-action1: add note on representation of `@version` not being semantic versioning, and noting issues with comparing floating point values (Gregg Kellogg)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#127]
add note on representation of `@version` not being semantic versioning, and noting issues with comparing floating point values (Gregg Kellogg) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-11-15-json-ld#action1))

Cc: @gkellogg

**Comment by gkellogg** [comment]
Closed via https://github.com/w3c/json-ld-syntax/pull/301 and https://github.com/w3c/json-ld-api/pull/218.
