### ISSUE TITLE
Set home page's for repos

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/json-ld-wg#13]
It'd be great if the header info (description, tags, homepage) here on GitHub were updated to include the publication URLs of each repo.

a) it's easier to find than "read directly" links in the readme
b) it's where people look first/most
c) it gets added to repo JSON in the API which is used by data scientist types and UX nerds like myself

Pretty please, @iherman? 😁

**Comment by BigBlueHat** [comment]
Thanks! 😄 There's actually a dedicated homepage field right next to the description. These links are in the description, so they're not in the JSON:
https://api.github.com/search/repositories?q=topic:json-ld-wg

Would you mind moving them? 🙁 Sorry for the "chore." I'd be happy to do it if I could!

**Comment by iherman** [comment]
Next time you should be more precise... :-)

Done.
