### ISSUE TITLE
Bogus automatic "Commit history" field in "Participate" spec headers.

### ISSUE THREAD

**Issue by davidlehn** [w3c/json-ld-wg#130]
The three specs have an automatic (?) "Commit history" field in the "Participate" section of the header.  They refer to "gh-pages" branches that don't exist.

**Comment by gkellogg** [comment]
Funny that the link checker didn’t notice.

**Comment by gkellogg** [comment]
Filed a bug: https://github.com/w3c/respec/issues/2582.
