### ISSUE TITLE
"Contributing" sections.

### ISSUE THREAD

**Issue by davidlehn** [w3c/json-ld-wg#131]
The "Contributing" sections are not in sync across the three specs.  It looks like the json-ld-syntax one is most correct since the last part refers to freenode IRC.  The others duplicate the w3 IRC references but with an invalid text hostname.

This looks like a good candidate section to extract into the wg repo 'common' dir, import it in each spec, and let current tools ensure the text is synced across repos.

There seems to be overlap between the "Contributing" section contents and the "Participate" links in the header.  What is the best practice for which info goes where and how to ensure people notice?  I can see one section being overlooked by readers if they see the other.  Duplicating all the links in both places doesn't seem ideal either.

- https://w3c.github.io/json-ld-syntax/#contributing
- https://w3c.github.io/json-ld-api/#contributing
- https://w3c.github.io/json-ld-framing/#contributing

**Comment by gkellogg** [comment]
Fixed in https://github.com/w3c/json-ld-framing/commit/ae59b2179d78fb2348ca7a752bfd2b6c7723803b and https://github.com/w3c/json-ld-api/commit/a1060cda38da07249745333fa15bfe20d4984019.

The Participate links are coming across many W3C specs and don't contradict this information.
