### ISSUE TITLE
2020-01-24-action1: create issue for ATRISK of entities within HTML script elements. (Gregg Kellogg)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#136]
create issue for ATRISK of entities within HTML script elements. (Gregg Kellogg) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-01-24-json-ld#action1))

Cc: @gkellogg

**Comment by gkellogg** [comment]
I believe @BigBlueHat has determined that there are JavaScript libraries other than xmldom (e.g., jsdom) which handle this properly, so there doesn't seem to be an issue with achieving adequate coverage on this feature.
