### ISSUE TITLE
2020-04-03-action1: send out APB about implementations--asking for folks to respond about their status (Benjamin Young)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#141]
send out APB about implementations--asking for folks to respond about their status (Benjamin Young) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-04-03-json-ld#action1))

Cc: @BigBlueHat

**Comment by jennet333** [comment]
@_Public []()

**Comment by iherman** [comment]
Overtaken by events
