### ISSUE TITLE
2020-04-24-action1: check pubrules on streaming note (Gregg Kellogg)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#145]
check pubrules on streaming note (Gregg Kellogg) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-04-24-json-ld#action1))

Cc: @gkellogg

**Comment by gkellogg** [comment]
@iherman I'm getting some unknown issues from Pub Rules checker:

> Deliverer not found. An attribute `data-deliverer` must be in the SotD.

I've never heard of this before; it's not set in our CR reports, and I don't see a reference to it from the ReSpec Wiki. Is there something specifically required for a WG-NOTE?

Also, the Link Checker seems to be broken.

**Comment by iherman** [comment]
@deniak I seem to remember that we had a problem with the `data-deliverer` before. Can you help, please?

**Comment by gkellogg** [comment]
The checker, and [Pubrules 4.1.8](https://www.w3.org/pubrules/doc/rules?profile=WG-NOTE#delivererID) say that it must have `data-deliverer` in SOTD, and apparently with the ID of the WG, is this just "JSON-LD WG", or is there a numeric ID I need to use?

It also says that it have the name of the W3C group, which is a link. That appears in the body of the first paragraph, so I suspect that's sufficient.

**Comment by iherman** [comment]
The ID is the groups numerical ID: 107714

@deniak is that correct?

**Comment by gkellogg** [comment]
Relevant (closed) ReSpec issue: https://github.com/w3c/respec/issues/1443

**Comment by deniak** [comment]
> The ID is the groups numerical ID: 107714
> 
> @deniak is that correct?

Correct. You can find all the rules with examples of markups at https://www.w3.org/pubrules/doc/rules/?profile=WG-NOTE

**Comment by gkellogg** [comment]
But, it seems that ReSpec should be doing this, which it's not, at least in 25.6.2.

**Comment by deniak** [comment]
Can you point me to the respec document?

**Comment by gkellogg** [comment]
https://github.com/w3c/json-ld-streaming/index.html.

Or, run through [specgen](https://labs.w3.org/spec-generator/?type=respec&url=https://raw.githack.com/w3c/json-ld-streaming/master/index.html?specStatus=WG-NOTE&shortName=json-ld11-streaming)

**Comment by gkellogg** [comment]
It may depend on an (undocumented) configuration variable `wgId`, looking at the source, I'll give that a try.

**Comment by gkellogg** [comment]
Yes, adding a `wgId` configuration variable seems to create it. I'll make sure the ReSpec Wiki documents this.

**Comment by deniak** [comment]
I'm not a respec expert but it may also rely on `wgPatentURI`:
https://github.com/w3c/respec/wiki/wgPatentURI

**Comment by deniak** [comment]
Yes, looking at https://github.com/w3c/respec/blob/develop/src/w3c/headers.js#L447 it's either `wgId`or `wgPatentURI` so 👍 to document `wgId`as well

**Comment by gkellogg** [comment]
Document had a wgPatentURI, but it didn't seem to take it from there.

**Comment by gkellogg** [comment]
Still seeing an error "Required patent policy paragraph not found.", even though it's in the document.

Also, there is a discrepancy in expectations on "FPWG-NOTE" vs "FPWD-NOTE", which I noted in w3c/respec#2852. I don't know if this would explain the error.

Link checker is back up, and links check out in the document.

**Comment by gkellogg** [comment]
@iherman I presume that, because this is a First Public note (FPWG-NOTE, depending on if ReSpec's FPWD-NOTE works okay), we'll need a snapshot created in the repo for publishing? What publication date shall we use?

**Comment by iherman** [comment]
@gkellogg we have to wait until the PR date is set. Yes, FPWD-NOTE should be fine.
