### ISSUE TITLE
2020-05-01-action1: create publication snapshots for 3 specs and streaming note. (Gregg Kellogg)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#147]
create publication snapshots for 3 specs and streaming note. (Gregg Kellogg) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-05-01-json-ld#action1))

Cc: @gkellogg

**Comment by gkellogg** [comment]
To publish as a PR, we need a `prEnd` date. I don't think we settled on one in the meeting.

cc/ @iherman @azaroth42 @BigBlueHat

**Comment by azaroth42** [comment]
prStart plus 6 weeks?

**Comment by gkellogg** [comment]
> On May 1, 2020, at 3:17 PM, Rob Sanderson <notifications@github.com> wrote:
> 
> 
> prStart plus 6 weeks?
> 
That would put prEnd at 18 June 2020. Make it official, and I’ll update the docs with that date. But, note that we are chartered through only 15 June 2020, so we may need to break with this and create a prEnd prior to that. Ivan?

Gregg

**Comment by iherman** [comment]
@gkellogg @azaroth42 @BigBlueHat 

I think we must keep to the 6 weeks' limit for the vote, so let us keep to the 18th of June. I will contact @swickr and @plehegar for the group charter break; I do not really foresee a problem with that.

**Comment by gkellogg** [comment]
Publication snapshots created.

## [JSON-LD 1.1 Syntax](https://w3c.github.io/json-ld-syntax/publication-snapshots/PR/Overview.html)

* No issues found.

## [JSON-LD 1.1 API](https://w3c.github.io/json-ld-api/publication-snapshots/PR/Overview.html)

* Added definition "JSON-LD input", which is used by Framing.
* No other issues found.

## [JSON-LD 1.1 Framing](https://w3c.github.io/json-ld-framing/publication-snapshots/PR/Overview.html)

* Link Checker complains that `https://www.w3.org/TR/json-ld11-api/#dfn-json-ld-input (lines 1410, 1420, 1430) is broken`, the definition was added to JSON-LD 1.1 API PR
* No other issues found.

## [JSON-lD 1.1 Streaming](https://w3c.github.io/json-ld-streaming/publication-snapshots/FPWD/Overview.html)

* Pubrules complains that `Required patent policy paragraph not found.`, but the document contains the following paragraph in the SOTD:
  > This document was produced by a group operating under the W3C Patent Policy. The group does not expect this document to become a W3C Recommendation.
* No other issues found.
