### ISSUE TITLE
Tagging policy

### ISSUE THREAD

**Issue by davidlehn** [w3c/json-ld-wg#149]
The various spec repos now have git tags like "CR", "PR", and "FPWD".  Those should really be versioned somehow since tags are not supposed to change and the repos may be used for future update with its own stages.  Perhaps the tags could be moved to X-1.1 or similar?  What do other specs do?  That won't change tags people have already pulled, but that's probably ok in this case.

**Comment by gkellogg** [comment]
We can change the tags to be dated. They were not formally necessary, but I considered them useful. I believe the CR and WD tags are dated.

**Comment by gkellogg** [comment]
I've created new tags that duplicate the untimestamped versions in the three repos.
