### ISSUE TITLE
Remove At Risk in -syntax and -api documents before final publication

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-wg#150]
We have some remaining Feature At Risk issues in Syntax and API; perhaps they should have been removed before PR publication.

Syntax:

* i18n Namespace - experimental feature
* rdf:CompoundLiteral - experimental feature

API:

* Deserialize JSON-LD to RDF Algorithm: rdfDirection on i18n-datatype and compound-literal options
* Serialize RDF as JSON-LD Algorithm: rdfDirection on i18n-datatype and compound-literal options

@iherman notes:

- looking at the implementation report I see that the features have been implemented by two independent implementations;
- we haven't received any pro or con reactions on these features by the RDF community.

I believe, also in view of the importance of these features, that this means these features, although originally at risk, should be considered as final in the documents. Ie, we have an editorial issue to handle when publishing the final Rec.

Note, b.t.w., that §10.3 and §10.4 in the syntax document, where these are specified, are marked as non-normative. In other words, and from hindsight, marking them as 'at risk' may not have been the best way to do it (but we know it was all a very special situation).

**Comment by BigBlueHat** [comment]
> We have some remaining Feature At Risk issues in Syntax and API; perhaps they should have been removed before PR publication.

@gkellogg to clarify the "they should have been removed before PR" is about the at risk notices (and _not_ the features themselves), correct?

Given w3c/json-ld-syntax#354 and w3c/json-ld-api#493 I'm certain that's the case, but would love to get that confirmed for posterity (as the opening issue sounds like the feature's sound be removed...).

**Comment by iherman** [comment]
——
Ivan Herman

(Written on my iPad. Excuses for brevity and misspellings...)

> On 8 Jun 2020, at 19:56, BigBlueHat <notifications@github.com> wrote:
> 
> ﻿
> We have some remaining Feature At Risk issues in Syntax and API; perhaps they should have been removed before PR publication.
> 
> @gkellogg to clarify the "they should have been removed before PR" is about the at risk notices (and not the features themselves), correct?
> 
> Given w3c/json-ld-syntax#354 and w3c/json-ld-api#493 I'm certain that's the case, but would love to get that confirmed for posterity (as the opening issue sounds like the feature's sound be removed...).
> 
That is exactly the case.

Ivan

**Comment by gkellogg** [comment]
Yes, as @iherman noted, both features have multiple implementations, so there is no need to remove them, which we really couldn't do now, anyway. We should have removed the "atrisk" notes at the end of CR. We just need a formal resolution to remove them now, before pulling the PR. This likely requires responses from more WG members.

**Comment by BigBlueHat** [comment]
I've requested that the @w3c/json-ld-wg members add their votes as comments to the two PRs (w3c/json-ld-syntax#354 and w3c/json-ld-api#493). We can then merge them and close this issue this time next week (June 15th) pending the correct results of the votes.

Thanks!
🎩

**Comment by gkellogg** [comment]
In advance of a recorded resolution, I merged the two PRs. One @BigBlueHat makes the vote official, we can record that here and close the issue.

**Comment by iherman** [comment]
I think that, in view of the  votes on the PR-s and the time available for raising any further issues, we can consider this issue as closed.
