### ISSUE TITLE
Add link to JSON-LD 1.0 earlier in the specs

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/json-ld-wg#22]
It's actually quite hard to navigate to a JSON-LD 1.0 spec from a JSON-LD 1.1 spec. I'd expected it in the "Previous version" metadata at the top.

Thoughts @gkellogg?

**Comment by gkellogg** [comment]
Missing `prevRecURI` configuration.

**Comment by gkellogg** [comment]
Fixed in https://github.com/w3c/json-ld-syntax/commit/04fe116ec6eb7e8b75499ed6755092a309b57655 and https://github.com/w3c/json-ld-api/commit/804113b3ffbd74a69ca4513fc8372df72107167d.
