### ISSUE TITLE
2019-02-08-action2: explore effect of `@nest+@container:@id` on compaction and expansion (Pierre-Antoine Champin)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#51]
explore effect of `@nest+@container:@id` on compaction and expansion (Pierre-Antoine Champin) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-02-08-json-ld#action2))

Cc: @pchampin

**Comment by azaroth42** [comment]
Closed in favor of #52
