### ISSUE TITLE
2019-01-25-action1: ping niklas about rdflib plans for 1.1 (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#54]
ping niklas about rdflib plans for 1.1 (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-01-25-json-ld#action1))

Cc: @azaroth42

**Comment by azaroth42** [comment]
@niklasl Do you have any plans around JSON-LD 1.1?

**Comment by niklasl** [comment]
@azaroth42 I do, but with no time secured, alas. (Our long-term project at work is scheduled go to into more of a maintenance mode sometime this year, possibly around summer, and I am planning for time to focus on JSON-LD 1.1 then, both for rdflib-jsonld and if possible to aid any remaining spec development in some way. As it is, I'm afraid I cannot dedicate any quality spare time for this, so my best bet is to have this endorsed by work. Which is fine in principle, albeit practically hard. So don't count me out entirely yet, I'm still lurking in the background. :wink:)

**Comment by iherman** [comment]
@azaroth42, I presume your action is done, ie, this can be closed...
