### ISSUE TITLE
2019-01-25-action2: write spec text of his mental model (Pierre-Antoine Champin)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#55]
write spec text of his mental model (Pierre-Antoine Champin) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-01-25-json-ld#action2))

Cc: @pchampin

**Comment by pchampin** [comment]
Done: w3c/json-ld-syntax#119 :-)
