### ISSUE TITLE
2019-01-18-action4: review azaroth's text and add further examples (Dave Longley)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#57]
review azaroth's text and add further examples (Dave Longley) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-01-18-json-ld#action4))

Cc: @dlongley

**Comment by dlongley** [comment]
Done here https://github.com/w3c/json-ld-syntax/issues/20 and other related examples and unit tests have been submitted here:

https://github.com/w3c/json-ld-syntax/issues/136
https://github.com/w3c/json-ld-api/pull/69
