### ISSUE TITLE
2019-01-18-action1: update the playground instead of scribing (David I. Lehn)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#59]
update the playground instead of scribing (David I. Lehn) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-01-18-json-ld#action1))

Cc: @davidlehn

**Comment by davidlehn** [comment]
We can leave this open if people find it as amusing as I do, but it would be more helpful to file issues in the json-ld.org repo for specific playground updates people would like.

**Comment by iherman** [comment]
This was a joke back then; I think you can safely close it:-)

**Comment by azaroth42** [comment]
:) Closing, but you're not off the hook to update the playground!
