### ISSUE TITLE
2018-10-26-action1: make a security consideration issue re relative IRI concatenation (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#60]
make a security consideration issue re relative IRI concatenation (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-26-json-ld#action1))

Cc: @azaroth42

**Comment by azaroth42** [comment]
Done: https://github.com/w3c/json-ld-syntax/issues/147
