### ISSUE TITLE
2018-10-26-action2: create security consideration re javascript URIs and relative IRIs (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#61]
create security consideration re javascript URIs and relative IRIs (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-26-json-ld#action2))

Cc: @azaroth42

**Comment by azaroth42** [comment]
Done: synatax#148
