### ISSUE TITLE
2018-10-25-action1: add privacy and horizontal review to guiding principles (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#63]
add privacy and horizontal review to guiding principles (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-25-json-ld#action1))

Cc: @azaroth42

**Comment by azaroth42** [comment]
Close as now vastly after the fact, as HR has been done.
