### ISSUE TITLE
2018-10-25-action3: create context signature issue, related to #20 (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#64]
create context signature issue, related to #20 (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-25-json-ld#action3))

Cc: @azaroth42

**Comment by azaroth42** [comment]
This was the SRI / metadata issue for contexts. Done.
