### ISSUE TITLE
2018-10-25-action6: raise a meta issue about BIDI and langString / HTML (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#65]
raise a meta issue about BIDI and langString / HTML (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-25-json-ld#action6))

Cc: @azaroth42

**Comment by azaroth42** [comment]
@ivan the action came from:
> It seems like we should raise the rdf:langString and rdf:HTML incompatibility to a higher power

But which higher power is that?

**Comment by iherman** [comment]
@azaroth42 I have no real recollection what this issue/action was all about!

But I _think_ these are issues around the fact that the base direction for literals (for Bidi) cannot be expressed in RDF except when using html literals. That problem is discussed in a separate [issue at the Publ WG](https://github.com/w3c/wpub/issues/354) and a reference possible work around a new RDF WG. I would think that this WG does not have to have any separate actions here (and I keep an eye on this issue elsewhere, in case a new RDF WG is created).

Propose closing.

**Comment by azaroth42** [comment]
+1 to closing. If there's a venue to raise the issue, then there's enough people who know about it that there's no need for a specific action at this point.
