### ISSUE TITLE
2018-10-25-action5: reach out to the TAG re #20 (Benjamin Young)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#66]
reach out to the TAG re #20 (Benjamin Young) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-25-json-ld#action5))

Cc: @bigbluehat

**Comment by azaroth42** [comment]
(Closing for Benjamin, as same as my reach out to tag, and both done)
