### ISSUE TITLE
2018-10-25-action2: create issues for ContextList and DocumentLoader editorial changes (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#67]
create issues for ContextList and DocumentLoader editorial changes (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-25-json-ld#action2))

Cc: @azaroth42

**Comment by azaroth42** [comment]
Done. syntax#149
