### ISSUE TITLE
2019-03-22-action1: provide example in issue frame/41 of `@omitdefault` need (Dave Longley)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#68]
provide example in issue frame/41 of `@omitdefault` need (Dave Longley) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-03-22-json-ld#action1))

Cc: @dlongley

**Comment by dlongley** [comment]
Provided an example here:

https://github.com/w3c/json-ld-framing/issues/41#issuecomment-476304375
