### ISSUE TITLE
2019-03-29-action1: facilitate decision by July 1 for TPAC (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#69]
facilitate decision by July 1 for TPAC (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-03-29-json-ld#action1))

Cc: @azaroth42

**Comment by azaroth42** [comment]
I think we're decided that we need it.
