### ISSUE TITLE
2019-03-29-action2: make an issue for security issue on IRI as term definition (Gregg Kellogg)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#70]
make an issue for security issue on IRI as term definition (Gregg Kellogg) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-03-29-json-ld#action2))

Cc: @gkellogg

**Comment by gkellogg** [comment]
Closed via https://github.com/w3c/json-ld-syntax/issues/155.
