### ISSUE TITLE
2019-04-19-action4: check a11y questionnaire against specs (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#77]
check a11y questionnaire against specs (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-04-19-json-ld#action4))

Cc: @azaroth42

**Comment by azaroth42** [comment]
Done. There's only one entry that actually affects us, and we're okay.

**Comment by BigBlueHat** [comment]
@azaroth42 could you elaborate? I've also gone through the FAST checklist, but didn't find anything that really applied to JSON-LD *itself*.

Here's my summary--based on a review of the <a href="https://w3c.github.io/apa/fast/checklist.html"><abbr title="Framework for Accessibility in the Specification of Technologies">FAST</abbr> Checklist</a>.

> JSON-LD is a data encoding format based on JSON. It does not itself dictate what is encoded in any JSON-LD document, nor how that content is used, displayed, or consumed. Consequently, the FAST checklist questions do not apply directly to any usage of JSON-LD syntax, API, or framing for encoding or processing data.

Whatever we determine, we should put it in writing and post that somewhere concretely--as people may ask again and URLs are faster than phone calls or emails. 😉

**Comment by azaroth42** [comment]
The second to last section applies to JSON-LD itself:

> If technology defines an API
> [] If the API can be used for structured content, it provides features to represent all aspects of the content including hidden accessibility features.

The API is used for structuring data, but the data itself is where the responsibility for accessibility features lies.

> [] If the API relies on user agents to generate a user interface, the specification provides guidance about accessibility requirements needed to enable full interaction with the API.

The API is not intended to generate a user interface directly.

**Comment by BigBlueHat** [comment]
Yeah, I'd read through those, but given that we don't explicitly convey a11y data, I wasn't sure they applied.

For instance, the first one has this in it's description:
> Some of the content richness can disappear if the API does not support features like content alternatives, control association, etc. Technologies that define APIs should ensure the API is rich enough to exchange all relevant accessibility information.

This would make sense for an API which processes a data/document format like HTML--which has a11y features (i.e. you shouldn't loose `aria-label` if your parsed the HTML). JSON-LD doesn't encode that data (knowingly).

Anyhow, what do you think about a variation on my summary + your two points?

**Comment by azaroth42** [comment]
Yep, I think that the heading means we need to check the boxes that we've considered them and they don't apply. The other headings rule out the sub-boxes, and thus we don't need to respond to them directly.

So :+1: on your summary plus the two points.

**Comment by BigBlueHat** [comment]
Just sent the following to the public APA list:
> Hi all,
>
> The JSON-LD WG is nearing publication of three specifications:
https://w3c.github.io/json-ld-syntax/
https://w3c.github.io/json-ld-api/
https://w3c.github.io/json-ld-framing/
>
> JSON-LD syntax is a data encoding format based on JSON. The API provides a means to convert JSON-LD documents into other forms of valid JSON-LD for further processing. Framing is used to reshape existing JSON-LD into a specific JSON tree structure.
>
> JSON-LD does not itself dictate what is encoded in any JSON-LD document, nor how that content is used, displayed, or consumed. The API simply enables usage of the encoded data. Consequently, most of the FAST checklist questions didn't seem to apply directly to usage of the JSON-LD syntax, API, or framing specifications.
>
> However, we did want to provide answers to the two API specific questions--which match the above summary:
>
>
> If technology defines an API...
> Q: If the API can be used for structured content, it provides features to represent all aspects of the content including hidden accessibility features.
>
> A: The API is used for structuring data, but the encoded data itself is where the responsibility for accessibility features lies.
>
>
>Q: If the API relies on user agents to generate a user interface, the specification provides guidance about accessibility requirements needed to enable full interaction with the API.
>
>A: The API is not intended to generate a user interface directly.
>
> Please let me know if you have other questions around JSON-LD and this summary from the checklist.

**Comment by BigBlueHat** [comment]
URL to the above message in the archives: https://lists.w3.org/Archives/Public/public-apa/2019Sep/0025.html
