### ISSUE TITLE
Communication with OGC

### ISSUE THREAD

**Issue by ajs6f** [w3c/json-ld-wg#82]
From: https://lists.w3.org/Archives/Public/public-json-ld-wg/2019Mar/0003.html

> Begin forwarded message:
> 
> From: Gobe Hobona <ghobona@opengeospatial.org>
> Subject: Draft OGC JSON Best Practice
> Date: March 7, 2019 at 9:14:38 AM GMT+1
> To: gregg@greggkellogg.net
> Cc: Linda van den Brink <l.vandenbrink@geonovum.nl>, Joan Masó Pau <joan.maso@uab.cat>
> 
> Dear Gregg,
> 
> The Architecture Domain Working Group of the the Open Geospatial Consortium (OGC) has been working on a JSON Best Practice for the geospatial community. The document is still in draft form but we would appreciate it if you could please share the link with the W3C JSON-LD community group. Any feedback is welcome.
> 
> https://github.com/opengeospatial/architecture-dwg/tree/master/json-best-practice <https://github.com/opengeospatial/architecture-dwg/tree/master/json-best-practice>
> 
> I have copied in Joan Maso, the chair of the Architecture Domain Working Group and editor of the draft OGC JSON Best Practice.
> 
> I have also copied in Linda van den Brink (Geonovum), the chair of the OGC-W3C Spatial Data on the Web Interest Group https://www.w3.org/2017/sdwig/ <https://www.w3.org/2017/sdwig/>
> 
> Regards,
> 
> Gobe
> 
> __________________________________________
> 
> Dr. Gobe Hobona, PhD MRICS
> Director, Knowledge Management
> Open Geospatial Consortium (OGC)
> OGC: Making location count.
> 
> http://www.linkedin.com/in/gobehobona <http://www.linkedin.com/in/gobehobona>
> Tel: +44 744 409 6781
> e-mail: ghobona@opengeospatial.org <mailto:ghobona@opengeospatial.org>
> www.opengeospatial.org

**Comment by azaroth42** [comment]
Closing.
