### ISSUE TITLE
2019-06-07-action4: add feature freeze note to the syntax, api, and framing READMEs and issue template for bugs only (Benjamin Young)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#84]
add feature freeze note to the syntax, api, and framing READMEs and issue template for bugs only (Benjamin Young) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-06-07-json-ld#action4))

Cc: @BigBlueHat

**Comment by BigBlueHat** [comment]
This is done. Huzzah. 😁
