### ISSUE TITLE
2019-06-07-action3: post blog reference for feature freeze (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#86]
post blog reference for feature freeze (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-06-07-json-ld#action3))

Cc: @azaroth42

**Comment by azaroth42** [comment]
Done: https://github.com/w3c/json-ld-syntax/issues/191#issuecomment-499965697
