### ISSUE TITLE
Complete Security Horizontal Review

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/json-ld-wg#89]
Responses to https://w3ctag.github.io/security-questionnaire/ from @azaroth42:

* 2.1 - The specification defines a data structure (a serialization for a graph data model) using which any information can be asserted. The specification itself allows for a "context" file to be published that maps between keys in a JSON object and RDF predicates. The benefit is high, as the serialization is easier to use than any other, and the risks are low, as the file contains only technical mapping information.

* 2.2 - Yes. The mapping file does not contain extraneous information, and there are no requirements for any fields to be present in the data instances.

* 2.3 - There is no PII used in the specifications

* 2.4 - There is no sensitive information used in the specifications.

* 2.5 - There is no new state information managed

* 2.6 - The mapping file can be requested from a URI, or embedded within a representation. The request patterns of clients for URI hosted mappings could be data-mined against the requester's IP address. However there is no way for the provider to know what the mapping is being used for, nor to see how the mapping is being applied, only that the client requested it like any other web resource.

* 2.7 - No sensor information is exposed

* 2.8 - As per 2.6, the only information delivered to the origin is the basic HTTP headers in order to request the mapping file.

* 2.9 - No new script execution mechanisms are enabled

* 2.10 - No access to other devices is enabled

* 2.11 - The specifications do not document any UI, and thus there is no control over it granted

* 2.12 - There are no temporary identifiers generated

* 2.13 - There is no distinction between first and third part usage.

* 2.14 - The specification works in "incognito" mode, as no state is necessary and it does not make any browser layer API requests

* 2.15 - The specification has these sections.

* 2.16 - The specification does not allow downgrading default security characteristics.

* 2.17 - None, it's very good! :)

**Comment by azaroth42** [comment]
Requested review

**Comment by azaroth42** [comment]
We will call this done after TPAC if still no concerns.

**Comment by gkellogg** [comment]
I see that the questionnaire was just updated https://www.w3.org/TR/security-privacy-questionnaire/
