### ISSUE TITLE
2019-08-16-action1: request an okay from PING on [https://github.com/w3c/json-ld-wg/issues/88](https://github.com/w3c/json-ld-wg/issues/88) (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#95]
request an okay from PING on [https://github.com/w3c/json-ld-wg/issues/88](https://github.com/w3c/json-ld-wg/issues/88) (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-08-16-json-ld#action1))

Cc: @azaroth42

**Comment by azaroth42** [comment]
Done.
