### ISSUE TITLE
2019-08-23-action5: add use absolute URIs to BPs (Adam Soroka)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#98]
add use absolute URIs to BPs (Adam Soroka) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-08-23-json-ld#action5))

Cc: @ajs6f

**Comment by ajs6f** [comment]
Hello, @iherman! Should we move this ticket to https://github.com/w3c/json-ld-bp/issues ?

**Comment by iherman** [comment]
@ajs6f Just raise an issue there and have this action closed with a reference. These issues are really used to keep track of the official actions taken at the call.

Do not forget to close #100, too, if you do it.

Thx!

**Comment by ajs6f** [comment]
Cool, @iherman, I made https://github.com/w3c/json-ld-bp/issues/11. But I don't have permissions to close issues here-- can you pull that trigger for me?

**Comment by BigBlueHat** [comment]
Closing in favor of https://github.com/w3c/json-ld-bp/issues/11

@ajs6f done. 😄
